### ISSUE TITLE
Error when configuring plugin.

### ISSUE THREAD

**Issue by madsamjp** [huynle/ogpt.nvim#15] opened 2024-01-13 01:40 UTC
I've installed the plugin using Packer and am trying to configure it. Here is how I've done it:
```lua
    use {"huynle/ogpt.nvim",
        requires = {
          "MunifTanjim/nui.nvim",
          "nvim-lua/plenary.nvim",
          "nvim-telescope/telescope.nvim"
    },
    config = function()
      require("ogpt").setup({
        default_provider = {
          name = "ollama",
          api_host = "http://10.0.10.100:11434",
        },
        api_params = {
          model = "mistral:7b-instruct-v0.2-q6_K",
          temperature = 0,
          top_p = 0.99,
        },
    })
    end,
  }

```
When I open nvim and try to run `OGPT` command, I get the following error:
```lua
Error executing Lua callback: ...pack/packer/start/ogpt.nvim/lua/ogpt/flows/chat/base.lua:48: attempt to index field 'popup_layout' (a nil value)
stack traceback:
        ...pack/packer/start/ogpt.nvim/lua/ogpt/flows/chat/base.lua:48: in function 'init'
        .../pack/packer/start/ogpt.nvim/lua/ogpt/common/classes.lua:88: in function 'new'
        ...pack/packer/start/ogpt.nvim/lua/ogpt/flows/chat/init.lua:13: in function 'open_chat'
        ...share/nvim/site/pack/packer/start/ogpt.nvim/lua/ogpt.lua:86: in function 'openChat'
        ...re/nvim/site/pack/packer/start/ogpt.nvim/plugin/ogpt.lua:2: in function <...re/nvim/site/pack/packer/start/ogpt.nvim/plugin/ogpt.lua:1>
```
Am I doing something wrong? Or is this a bug?

**Comment by monkeyxite** [comment] 2024-01-15 09:00
same error after fetching latest TexGenUI commit.

**Comment by huynle** [comment] 2024-01-25 13:22
Sorry for the late reply here, I'm not exactly sure what happened in your setup. try pulling latest main, and test again? I can help you after that.

**Comment by LudoPinelli** [comment] 2024-01-26 04:57
I have nearly the same pb, but as soon as I launch nvim:
```
...nfig/local/share/nvim/lazy/ogpt.nvim/lua/ogpt/config.lua:289: bad argument #1 to 'pairs' (table expected, got nil)

# stacktrace:
  - /ogpt.nvim/lua/ogpt/config.lua:289 _in_ **setup**
  - /ogpt.nvim/lua/ogpt.lua:29 _in_ **setup**
  - ~/.config/nvim/lua/plugins/ai/ogpt.lua:5 _in_ **config**
```

My config (Lazy):
```
return {
  "huynle/ogpt.nvim",
  dependencies = {
    "MunifTanjim/nui.nvim",
    "nvim-lua/plenary.nvim",
    "nvim-telescope/telescope.nvim",
  },
  event = "VeryLazy",
  config = function()
    require("ogpt").setup({
      default_provider = {
        model = "codellama",
      },
    })
  end,
}
```

The plugin is up to date with the latest main.

**Comment by sandangel** [comment] 2024-01-30 16:43
@LudoPinelli need to change this: 

https://github.com/huynle/ogpt.nvim/blob/main/lua/ogpt/config.lua#L289

to 

```lua
    for key, item in pairs(M.options[to_replace]) do
      M.options[to_replace][key] = item
    end

```

**Comment by LudoPinelli** [comment] 2024-01-30 17:23
Thank you!

**Comment by huynle** [comment] 2024-01-31 11:19
anyone here wants to test out the dev branch and give some feedback?

**Comment by sandangel** [comment] 2024-01-31 14:46
@huynle I got this error:

```sh
   Error  23:45:02 msg_show.lua_error Error executing Lua callback: ...yen/.local/share/nvim/lazy/ogpt.nvim/lua/ogpt/config.lua:363: attempt to index a nil value
stack traceback:
	...yen/.local/share/nvim/lazy/ogpt.nvim/lua/ogpt/config.lua:363: in function 'get_chat_params'
	...l/share/nvim/lazy/ogpt.nvim/lua/ogpt/flows/chat/base.lua:48: in function 'init'
	...al/share/nvim/lazy/ogpt.nvim/lua/ogpt/common/classes.lua:88: in function 'new'
	...l/share/nvim/lazy/ogpt.nvim/lua/ogpt/flows/chat/init.lua:13: in function 'open_chat'
	...san.nguyen/.local/share/nvim/lazy/ogpt.nvim/lua/ogpt.lua:84: in function 'openChat'
	....nguyen/.local/share/nvim/lazy/ogpt.nvim/plugin/ogpt.lua:3: in function <....nguyen/.local/share/nvim/lazy/ogpt.nvim/plugin/ogpt.lua:1>
   Error  23:45:02 notify.error lazy.nvim Failed to run `config` for ogpt.nvim

...yen/.local/share/nvim/lazy/ogpt.nvim/lua/ogpt/config.lua:336: bad argument #1 to 'pairs' (table expected, got nil)

# stacktrace:
  - /ogpt.nvim/lua/ogpt/config.lua:336 _in_ **setup**
  - /ogpt.nvim/lua/ogpt.lua:28 _in_ **setup**
```

my config:

```lua
  {
    'huynle/ogpt.nvim',
    branch = 'dev',
    keys = {
      {
        '<leader>a',
        '<cmd>OGPT<CR>',
        desc = 'GenAI nvim prompt',
        mode = { 'n', 'x' },
      },
    },
    opts = {
      default_provider = {
        name = 'ollama',
        api_host = 'http://172.16.129.1:11434',
        model = 'codellama:70b-instruct',
      },
    },
    dependencies = {
      'MunifTanjim/nui.nvim',
      'nvim-lua/plenary.nvim',
      'nvim-telescope/telescope.nvim'
    }
  },

```

**Comment by huynle** [comment] 2024-01-31 17:00
yes, the configuration got updated. This new structure will allow our users to specify, a provider, and/or model for each action/popup/chat. if you dont specify it, it will use the default provider, and default provider's model.

```lua
  {
    'huynle/ogpt.nvim',
    branch = 'dev',
    keys = {
      {
        '<leader>a',
        '<cmd>OGPT<CR>',
        desc = 'GenAI nvim prompt',
        mode = { 'n', 'x' },
      },
    },
    opts = {
      default_provider = 'ollama',
      providers = {
        ollama = {
          api_host = 'http://172.16.129.1:11434',
          model = 'codellama:70b-instruct',
      },
    },
    dependencies = {
      'MunifTanjim/nui.nvim',
      'nvim-lua/plenary.nvim',
      'nvim-telescope/telescope.nvim'
    }
  },

```

**Comment by LudoPinelli** [comment] 2024-01-31 19:36
> anyone here wants to test out the dev branch and give some feedback?

I will for the next few days.

(P.S.: I'm not sure having codellama:70b as a default provider's model is a good idea, it could make most computers explode :D)

**Comment by sandangel** [comment] 2024-01-31 22:45
@huynle I got this error when copy your config:

```sh
...yen/.local/share/nvim/lazy/ogpt.nvim/lua/ogpt/config.lua:336: bad argument #1 to 'pairs' (table expected, got nil)

# stacktrace:
  - /ogpt.nvim/lua/ogpt/config.lua:336 _in_ **setup**
  - /ogpt.nvim/lua/ogpt.lua:28 _in_ **setup**

```

**Comment by sandangel** [comment] 2024-01-31 22:49
@huynle This line

https://github.com/huynle/ogpt.nvim/blob/dev/lua/ogpt/config.lua#L336

need to be changed to 

```lua
for key, item in pairs(M.options[to_replace]) do
```

Notice that we're using `M.options` instead of `options`

**Comment by huynle** [comment] 2024-02-01 11:28
> @huynle This line
> 
> https://github.com/huynle/ogpt.nvim/blob/dev/lua/ogpt/config.lua#L336
> 
> need to be changed to
> 
> ```lua
> for key, item in pairs(M.options[to_replace]) do
> ```
> 
> Notice that we're using `M.options` instead of `options`

Thanks for check that, but I believe that is correct. `options` is the table that are given by the user during plugin setup.  Those options are all overlay on top of the default `M.defaults`, EXCEPT for the `actions` key-value pairs. If any is given by the user, those will completely overwrite the default.

For example you want to update the "edit_with_instruction" action, you have to specify the entire action, and not just a field inside the action and hoping that you can use the default fields.

**Comment by huynle** [comment] 2024-02-01 11:30
if you use the "actions_paths" option in your configurations, those will have the final say in your actions - https://github.com/huynle/ogpt.nvim/blob/810c0865f3b5aab2b2a05d433c4e27fc1405770d/lua/ogpt/flows/actions/init.lua#L40-L52

**Comment by sandangel** [comment] 2024-02-01 11:59
THe problem is we have the error from the config you shared with me.

**Comment by huynle** [comment] 2024-02-01 12:08
what is the problem? what is your full configuration, can you send some snippets, or traceback so i can see?

**Comment by sandangel** [comment] 2024-02-01 14:22
https://github.com/huynle/ogpt.nvim/issues/15#issuecomment-1920113671
https://github.com/huynle/ogpt.nvim/issues/15#issuecomment-1919526237

**Comment by DragonScarlet** [comment] 2024-02-01 15:55
Same problem as @sandangel 
I just wanted to install the plugin as it shown.
And i get the same problem.
..yen/.local/share/nvim/lazy/ogpt.nvim/lua/ogpt/config.lua:336: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by huynle** [comment] 2024-02-01 22:40
it should be fixed now, my configuration always have "actions" field since i run a lot of different actions. you guys are using bare minimum, so that was the cause of the issue.

**Comment by huynle** [comment] 2024-02-16 22:41
all should be fixed for this issue!

**Closed as completed by huynle** 2024-02-16 22:41 UTC
